package com.dao;

import com.model.LikeTie;
import com.model.LikeTieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LikeTieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_tie
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    int countByExample(LikeTieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_tie
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    int deleteByExample(LikeTieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_tie
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    int insert(LikeTie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_tie
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    int insertSelective(LikeTie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_tie
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    List<LikeTie> selectByExample(LikeTieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_tie
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") LikeTie record, @Param("example") LikeTieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_tie
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    int updateByExample(@Param("record") LikeTie record, @Param("example") LikeTieExample example);
}