package com.dao;

import com.model.Liuyan;
import com.model.LiuyanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiuyanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    int countByExample(LiuyanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    int deleteByExample(LiuyanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    int deleteByPrimaryKey(Integer liuyanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    int insert(Liuyan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    int insertSelective(Liuyan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    List<Liuyan> selectByExampleWithBLOBs(LiuyanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    List<Liuyan> selectByExample(LiuyanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    Liuyan selectByPrimaryKey(Integer liuyanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") Liuyan record, @Param("example") LiuyanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Liuyan record, @Param("example") LiuyanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    int updateByExample(@Param("record") Liuyan record, @Param("example") LiuyanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    int updateByPrimaryKeySelective(Liuyan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Liuyan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    int updateByPrimaryKey(Liuyan record);
}