package com.dao;

import com.model.Tie;
import com.model.TieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int countByExample(TieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int deleteByExample(TieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int deleteByPrimaryKey(Integer tieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int insert(Tie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int insertSelective(Tie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    List<Tie> selectByExampleWithBLOBs(TieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    List<Tie> selectByExample(TieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    Tie selectByPrimaryKey(Integer tieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") Tie record, @Param("example") TieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Tie record, @Param("example") TieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int updateByExample(@Param("record") Tie record, @Param("example") TieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int updateByPrimaryKeySelective(Tie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Tie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tie
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int updateByPrimaryKey(Tie record);
}