package com.dao;

import com.model.Zan;
import com.model.ZanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int countByExample(ZanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int deleteByExample(ZanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int insert(Zan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int insertSelective(Zan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    List<Zan> selectByExample(ZanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") Zan record, @Param("example") ZanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    int updateByExample(@Param("record") Zan record, @Param("example") ZanExample example);
}