package com.model;

public class Leibie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leibie.leibie_id
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    private Integer leibieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leibie.body
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    private String body;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leibie.leibie_id
     *
     * @return the value of leibie.leibie_id
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public Integer getLeibieId() {
        return leibieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leibie.leibie_id
     *
     * @param leibieId the value for leibie.leibie_id
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public void setLeibieId(Integer leibieId) {
        this.leibieId = leibieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leibie.body
     *
     * @return the value of leibie.body
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leibie.body
     *
     * @param body the value for leibie.body
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }
}