package com.model;

import java.util.ArrayList;
import java.util.List;

public class LeibieExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public LeibieExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLeibieIdIsNull() {
            addCriterion("leibie_id is null");
            return (Criteria) this;
        }

        public Criteria andLeibieIdIsNotNull() {
            addCriterion("leibie_id is not null");
            return (Criteria) this;
        }

        public Criteria andLeibieIdEqualTo(Integer value) {
            addCriterion("leibie_id =", value, "leibieId");
            return (Criteria) this;
        }

        public Criteria andLeibieIdNotEqualTo(Integer value) {
            addCriterion("leibie_id <>", value, "leibieId");
            return (Criteria) this;
        }

        public Criteria andLeibieIdGreaterThan(Integer value) {
            addCriterion("leibie_id >", value, "leibieId");
            return (Criteria) this;
        }

        public Criteria andLeibieIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("leibie_id >=", value, "leibieId");
            return (Criteria) this;
        }

        public Criteria andLeibieIdLessThan(Integer value) {
            addCriterion("leibie_id <", value, "leibieId");
            return (Criteria) this;
        }

        public Criteria andLeibieIdLessThanOrEqualTo(Integer value) {
            addCriterion("leibie_id <=", value, "leibieId");
            return (Criteria) this;
        }

        public Criteria andLeibieIdIn(List<Integer> values) {
            addCriterion("leibie_id in", values, "leibieId");
            return (Criteria) this;
        }

        public Criteria andLeibieIdNotIn(List<Integer> values) {
            addCriterion("leibie_id not in", values, "leibieId");
            return (Criteria) this;
        }

        public Criteria andLeibieIdBetween(Integer value1, Integer value2) {
            addCriterion("leibie_id between", value1, value2, "leibieId");
            return (Criteria) this;
        }

        public Criteria andLeibieIdNotBetween(Integer value1, Integer value2) {
            addCriterion("leibie_id not between", value1, value2, "leibieId");
            return (Criteria) this;
        }

        public Criteria andBodyIsNull() {
            addCriterion("body is null");
            return (Criteria) this;
        }

        public Criteria andBodyIsNotNull() {
            addCriterion("body is not null");
            return (Criteria) this;
        }

        public Criteria andBodyEqualTo(String value) {
            addCriterion("body =", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotEqualTo(String value) {
            addCriterion("body <>", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyGreaterThan(String value) {
            addCriterion("body >", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyGreaterThanOrEqualTo(String value) {
            addCriterion("body >=", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLessThan(String value) {
            addCriterion("body <", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLessThanOrEqualTo(String value) {
            addCriterion("body <=", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLike(String value) {
            addCriterion("body like", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotLike(String value) {
            addCriterion("body not like", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyIn(List<String> values) {
            addCriterion("body in", values, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotIn(List<String> values) {
            addCriterion("body not in", values, "body");
            return (Criteria) this;
        }

        public Criteria andBodyBetween(String value1, String value2) {
            addCriterion("body between", value1, value2, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotBetween(String value1, String value2) {
            addCriterion("body not between", value1, value2, "body");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table leibie
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 20 19:29:05 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table leibie
     *
     * @mbggenerated Tue Jun 20 19:29:05 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}