package com.model;

public class LikeTie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_tie.user_id
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_tie.tie_id
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    private Integer tieId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_tie.user_id
     *
     * @return the value of like_tie.user_id
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_tie.user_id
     *
     * @param userId the value for like_tie.user_id
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_tie.tie_id
     *
     * @return the value of like_tie.tie_id
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public Integer getTieId() {
        return tieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_tie.tie_id
     *
     * @param tieId the value for like_tie.tie_id
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public void setTieId(Integer tieId) {
        this.tieId = tieId;
    }
}