package com.model;

import java.util.Date;

public class Liuyan {
	
	private String time;
	private String userName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.liuyanId
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    private Integer liuyanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.user_id
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.tie_id
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    private Integer tieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.createtime
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.body
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    private String body;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.liuyanId
     *
     * @return the value of liuyan.liuyanId
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    public Integer getLiuyanid() {
        return liuyanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.liuyanId
     *
     * @param liuyanid the value for liuyan.liuyanId
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    public void setLiuyanid(Integer liuyanid) {
        this.liuyanid = liuyanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.user_id
     *
     * @return the value of liuyan.user_id
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.user_id
     *
     * @param userId the value for liuyan.user_id
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.tie_id
     *
     * @return the value of liuyan.tie_id
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    public Integer getTieId() {
        return tieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.tie_id
     *
     * @param tieId the value for liuyan.tie_id
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    public void setTieId(Integer tieId) {
        this.tieId = tieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.createtime
     *
     * @return the value of liuyan.createtime
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.createtime
     *
     * @param createtime the value for liuyan.createtime
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.body
     *
     * @return the value of liuyan.body
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.body
     *
     * @param body the value for liuyan.body
     *
     * @mbggenerated Mon Jul 03 17:13:02 CST 2017
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
    
    
}