package com.model;

import java.util.Date;

public class Tie {
	
	private String userName;
	private String time;
	private String leibieName;
	private int zan;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tie.tie_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    private Integer tieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tie.user_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tie.leibie_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    private Integer leibieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tie.title
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tie.guanjianzi
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    private String guanjianzi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tie.liulan
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    private Integer liulan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tie.createtime
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tie.dengji
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    private Integer dengji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tie.tie_content
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    private String tieContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tie.tie_id
     *
     * @return the value of tie.tie_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public Integer getTieId() {
        return tieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tie.tie_id
     *
     * @param tieId the value for tie.tie_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public void setTieId(Integer tieId) {
        this.tieId = tieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tie.user_id
     *
     * @return the value of tie.user_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tie.user_id
     *
     * @param userId the value for tie.user_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tie.leibie_id
     *
     * @return the value of tie.leibie_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public Integer getLeibieId() {
        return leibieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tie.leibie_id
     *
     * @param leibieId the value for tie.leibie_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public void setLeibieId(Integer leibieId) {
        this.leibieId = leibieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tie.title
     *
     * @return the value of tie.title
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tie.title
     *
     * @param title the value for tie.title
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tie.guanjianzi
     *
     * @return the value of tie.guanjianzi
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public String getGuanjianzi() {
        return guanjianzi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tie.guanjianzi
     *
     * @param guanjianzi the value for tie.guanjianzi
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public void setGuanjianzi(String guanjianzi) {
        this.guanjianzi = guanjianzi == null ? null : guanjianzi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tie.liulan
     *
     * @return the value of tie.liulan
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public Integer getLiulan() {
        return liulan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tie.liulan
     *
     * @param liulan the value for tie.liulan
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public void setLiulan(Integer liulan) {
        this.liulan = liulan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tie.createtime
     *
     * @return the value of tie.createtime
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tie.createtime
     *
     * @param createtime the value for tie.createtime
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tie.dengji
     *
     * @return the value of tie.dengji
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public Integer getDengji() {
        return dengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tie.dengji
     *
     * @param dengji the value for tie.dengji
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public void setDengji(Integer dengji) {
        this.dengji = dengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tie.tie_content
     *
     * @return the value of tie.tie_content
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public String getTieContent() {
        return tieContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tie.tie_content
     *
     * @param tieContent the value for tie.tie_content
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public void setTieContent(String tieContent) {
        this.tieContent = tieContent == null ? null : tieContent.trim();
    }

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getLeibieName() {
		return leibieName;
	}

	public void setLeibieName(String leibieName) {
		this.leibieName = leibieName;
	}

	public int getZan() {
		return zan;
	}

	public void setZan(int zan) {
		this.zan = zan;
	}
    
    
}