package com.model;

import java.util.Date;

public class User {
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.headerimg
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    private String headerimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.quanxian_id
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    private Integer quanxianId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createtime
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.headerimg
     *
     * @return the value of user.headerimg
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public String getHeaderimg() {
        return headerimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.headerimg
     *
     * @param headerimg the value for user.headerimg
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public void setHeaderimg(String headerimg) {
        this.headerimg = headerimg == null ? null : headerimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.quanxian_id
     *
     * @return the value of user.quanxian_id
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public Integer getQuanxianId() {
        return quanxianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.quanxian_id
     *
     * @param quanxianId the value for user.quanxian_id
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public void setQuanxianId(Integer quanxianId) {
        this.quanxianId = quanxianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createtime
     *
     * @return the value of user.createtime
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createtime
     *
     * @param createtime the value for user.createtime
     *
     * @mbggenerated Tue Jun 20 19:29:04 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    
}