package com.model;

public class Zan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.tie_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    private Integer tieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.user_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.tie_id
     *
     * @return the value of zan.tie_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public Integer getTieId() {
        return tieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.tie_id
     *
     * @param tieId the value for zan.tie_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public void setTieId(Integer tieId) {
        this.tieId = tieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.user_id
     *
     * @return the value of zan.user_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.user_id
     *
     * @param userId the value for zan.user_id
     *
     * @mbggenerated Thu Jun 22 15:44:56 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}